#!/bin/sh
#
# PROVIDE: gitea
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="gitea"
rcvar="gitea_enable"

load_rc_config $name

: ${gitea_enable="NO"}

command="/root/gitea/gitea"
command_args="web"
pidfile="/var/run/${name}.pid"
logfile="/var/log/${name}.log"

procname="${command}"

command_interpreter="/usr/sbin/daemon"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

gitea_start() {
    echo "Starting ${name}."
    # echo "$HBOX_STORAGE_DATA"
    # echo "$HBOX_MODE"
    # echo "$HBOX_STORAGE_SQLITE_URL"
    ${command_interpreter} -u ${name} -o ${logfile} -P ${pidfile} -- ${command} ${command_args}
}

gitea_stop() {
    echo "Stopping ${name}."
    kill -TERM $(cat ${pidfile})
}

run_rc_command "$1"
